CREATE TABLE "CATEGORY"(
    category_no NUMBER PRIMARY KEY,
    category_name VARCHAR2(20) NOT NULL
);
CREATE TABLE "USER"(
    user_no NUMBER PRIMARY KEY,
    category_no NUMBER,
    user_id VARCHAR2(100) NOT NULL UNIQUE,
    user_pw VARCHAR2(100) NOT NULL,
    user_name VARCHAR2(20) NOT NULL UNIQUE,
    phone CHAR(13) NULL,
    email VARCHAR2(100) NOT NULL,
    addr VARCHAR2(100) NULL
);

ALTER TABLE "USER" ADD CONSTRAINT category_no_foreign_key 
FOREIGN KEY(category_no) REFERENCES "CATEGORY"(category_no) ON DELETE CASCADE;

CREATE TABLE NOTICE(
    NOTICE_NO NUMBER PRIMARY KEY,
    NOTICE_WRITER VARCHAR2(20) NOT NULL,
    NOTICE_TITLE VARCHAR2(100) NOT NULL,
    NOTICE_CONTENT VARCHAR2(4000),
    FILENAME VARCHAR2(100),
    FILEPATH VARCHAR2(100),
    ENROLL_DATE DATE
);
ALTER TABLE NOTICE ADD CONSTRAINT NOTICE_WRITER_FORIEIGN_KEY
FOREIGN KEY(NOTICE_WRITER) REFERENCES "USER"(USER_NAME) ON DELETE set null;

CREATE TABLE "ADMIN"(
    ADMIN_NO NUMBER PRIMARY KEY,
    ADMIN_ID VARCHAR2(20) NOT NULL UNIQUE,
    ADMIN_PW VARCHAR2(100) NOT NULL,
    NICKNAME VARCHAR2(20)
);

CREATE TABLE BOOK(
    BOOK_NO NUMBER PRIMARY KEY,
    BOOK_NAME VARCHAR2(100),
    BOOK_KIND VARCHAR2(100),
    BOOK_WRITER VARCHAR2(50),
    BOOK_PUBLISHER VARCHAR2(50),
    BOOK_INTRODUCE VARCHAR2(500),
    IMAGEURL VARCHAR2(100)
);

CREATE TABLE BOOK_RENTAL_RESERVE(
    BOOK_RENTAL_RESERVE_NO NUMBER PRIMARY KEY,
    BOOK_NO NUMBER ,
    USER_NO NUMBER 
);

ALTER TABLE BOOK_RENTAL_RESERVE ADD CONSTRAINT BOOK_RENTAL_RESERVE_BOOK_NO_FK
FOREIGN KEY(BOOK_NO) REFERENCES BOOK(BOOK_NO) ON DELETE CASCADE;

ALTER TABLE BOOK_RENTAL_RESERVE ADD CONSTRAINT BOOK_RENTAL_RESERVE_USER_NO_FK
FOREIGN KEY(USER_NO) REFERENCES "USER"(USER_NO) ON DELETE CASCADE;

CREATE TABLE RENTAL_LOCATION(
    RENTAL_LOCATION_NO NUMBER PRIMARY KEY,
    PLACENAME VARCHAR2(50),
    ADDR VARCHAR2(300),
    PHONE VARCHAR(20)
);
CREATE TABLE BOOK_RENTAL(
    BOOK_RENTAL_NO NUMBER PRIMARY KEY,
    USER_NO NUMBER ,
    BOOK_NO NUMBER ,
    RENTAL_LOCATION_NO NUMBER NOT NULL,
    ENROLL_DATE DATE,
    RETURN_DATE DATE
);
ALTER TABLE BOOK_RENTAL ADD CONSTRAINT BOOK_RENTAL_USER_NO_Fk
FOREIGN KEY(USER_NO) REFERENCES "USER"(USER_NO) ON DELETE CASCADE;

ALTER TABLE BOOK_RENTAL ADD CONSTRAINT BOOK_RENTAL_BOOK_NO_FK
FOREIGN KEY(BOOK_NO) REFERENCES BOOK(BOOK_NO) ON DELETE CASCADE;

ALTER TABLE BOOK_RENTAL ADD CONSTRAINT BOOK_RENTAL_LOCATION_NO_FK
FOREIGN KEY(RENTAL_LOCATION_NO) REFERENCES RENTAL_LOCATION(RENTAL_LOCATION_NO) ON DELETE SET NULL;

CREATE TABLE BOOK_PROPOSAL(
    BOOK_PROPOSAL_NO NUMBER PRIMARY KEY,
    USER_NO NUMBER ,
    BOOK_NO NUMBER ,
    BOOK_WRITER VARCHAR2(50),
    BOOK_PUBLISHER VARCHAR2(50),
    REASON VARCHAR2(200)
);

ALTER TABLE BOOK_PROPOSAL ADD CONSTRAINT BOOK_PROPOSAL_USER_NO_FK
FOREIGN KEY(USER_NO) REFERENCES "USER"(USER_NO) ON DELETE SET NULL;

ALTER TABLE BOOK_PROPOSAL ADD CONSTRAINT BOOK_PROPOSAL_BOOK_NO_FK
FOREIGN KEY(BOOK_NO) REFERENCES BOOK(BOOK_NO) ON DELETE SET NULL;

CREATE TABLE BOOK_REVIEW(
    BOOK_REVIEW_NO NUMBER PRIMARY KEY,
    BOOK_NO NUMBER,
    USER_NAME VARCHAR2(20),
    TITLE VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(4000),
    RATING NUMBER,
    ENROLL_DATE DATE
);

ALTER TABLE BOOK_REVIEW ADD CONSTRAINT BOOK_REVIEW_BOOK_NO_FK
FOREIGN KEY(BOOK_NO) REFERENCES BOOK(BOOK_NO) ON DELETE SET NULL;


ALTER TABLE BOOK_REVIEW ADD CONSTRAINT BOOK_REVIEW_USER_NAME_FK
FOREIGN KEY(USER_NAME) REFERENCES "USER"(USER_NAME) ON DELETE SET NULL;

create table book_favorites(
    book_favorites_no number primary key,
    user_no number,
    book_no number
);

ALTER TABLE BOOK_favorites ADD CONSTRAINT BOOK_favorites_USER_no_FK
FOREIGN KEY(book_No) REFERENCES book(book_No) ON DELETE CASCADE;


ALTER TABLE BOOK_favorites ADD CONSTRAINT BOOK_favorites_book_no_FK
FOREIGN KEY(USER_No) REFERENCES "USER"(USER_No) ON DELETE CASCADE;

CREATE TABLE CALENDAR(
    CALENDAR_NO NUMBER PRIMARY KEY,
    CALENDAR_TITLE VARCHAR2(100),
    CALENDAR_STARTDATE DATE,
    CALENDAR_ENDDATE DATE
);

create table image(
    image_no number primary key,
    tableName varchar2(20) not null,
    filename varchar2(50),
    filepath varchar2(50)
);

create sequence notice_seq;
create sequence admin_seq;
create sequence calendar_seq;
create sequence book_proposal_seq;
create sequence book_favorites_seq;
create sequence book_review_seq;
create sequence book_rental_reserve_seq;
create sequence rental_location_seq;
create sequence book_rental_seq;
create sequence book_seq;
create sequence user_seq;
create sequence category_seq;
create sequence image_seq;